### ISSUE TITLE
Xcode 8 App is Crash

### ISSUE THREAD

**Issue by shravanteegala** [bigfish24/ABFRealmSearchViewController#14]
when i load [super ViewDidLoad]
my App is Crashed plz help me.

**Comment by bigfish24** [comment]
Can you provide more details? Or a reproduction case?

**Comment by bigfish24** [comment]
Closing from comments here: https://github.com/bigfish24/ABFRealmSearchViewController/issues/13

**Comment by shravanteegala** [comment]
Thank you,
I resolve this one to change 
to isViewLoaded  property.

**Comment by bigfish24** [comment]
👍
