### ISSUE TITLE
Override 'searchPredicate(text: String?) -> NSPredicate?'

### ISSUE THREAD

**Issue by bcamur** [bigfish24/ABFRealmSearchViewController#4]
Hi, I want to override the searchPredicate function but I can't since it is private. I tried to override refreshSearchResults() since it is public but then I can't access searchQueue property, since it is private. Can you offer another solution? Thanks

**Comment by bigfish24** [comment]
There is a `basePredicate` property that you can override to add additional filtering to the text filtering.

**Comment by bcamur** [comment]
I am using a predicate like this: NSPredicate(format: "ANY messages.value CONTAINS[c] %@", text) so I can't set the base predicate with a constant. I forked the project and made overriding searchPredicate possible to solve the problem for now, which seems to work.
