### ISSUE TITLE
RealmSwift & objectivec

### ISSUE THREAD

**Issue by adriantofan** [bigfish24/ABFRealmSearchViewController#6]
Hello, please help me understand the following. From the RealmSwift documentation :

> If you’re looking to use Realm from Objective‑C, or from mixed Objective‑C & Swift apps please see Realm Objective‑C instead.
> The Realm Objective‑C and Realm Swift APIs are not interoperable and using them together is not supported.

ABFRealmSearchViewController uses internal RBQFetchedResultsController. As far as I understand, at least according to XCode, RBQFetchedResultsController is a bunch of objective-c files so it must use objective-c api. 
Can you share your thoughts with me about this issue?
Thank you

**Comment by adriantofan** [comment]
I am droping Realm for my current project. sorry about bothering you

**Comment by bigfish24** [comment]
Sorry to hear this! The documentation point is specifically addressing the interoperability of the Realm Swift and ObjC APIs. However, technically, Realm Swift is simply an API that follows more Swift design patterns but underneath it uses the ObjC API. As a result, technically Realm Swift and Realm ObjC work together, you just can't take a Realm `Object` from Swift and use it in place of a `RLMObject` in ObjC.

RBQFRC works off of Realm's ObjC API directly, but then similar to Realm Swift, I built a Swift friendly API on top of it that uses the Realm Swift objects vs the Realm ObjC objects.

Would be curious to know why you are dropping Realm!

**Comment by adriantofan** [comment]
I've had many small problems with Realm, like the NSDate is truncated to the second combined with lack of auto-incrementing properties and limits regarding to indexing and primary keys. Finally, I've used some  reusable components recommended on realm website and I find them not quite suitable to my use case.  I didn't particularly like this lack of clarity about Swift and Objective-C compatibility. In the end if I need to replicate CoreData so why just not use CoreData ? Maybe next project when things will mature or I will have more time.
